### ISSUE TITLE
Please expand tutorial documentation 

### ISSUE THREAD

**Issue by DagnyTagg2013** [victrcodes/akka-sample-twitter-streaming#2]
Hi there!

Was hoping if you could please expand the tutorial documentation to provide a baseline understanding of the different API abstraction levels, and how they fit together.

I had  posted my specific questions on this tutorial in the Disqus comments section here:
http://www.lightbend.com/activator/template/akka-sample-twitter-streaming

"I also had questions about proper usage of this API and understanding the basics about how it works under-the-hood."

**Comment by victrcodes** [comment]
This is a very bare-bones example, so for any akka related documentation you should just go to http://doc.akka.io/docs/akka/2.4/scala/http/index.html

As for other questions, please ask one question per issue.
